# Mysql Configuration
# spring:
#     datasource:
#         url: jdbc:mysql://localhost:3306/springdesk
#         username: root
#         password: edi
#     jpa:
#         show-sql: true
#         hibernate:
#             ddl-auto: create
#         properties:
#             hibernate:
#             dialect: org.hibernate.dialect.MySQL8Dialect
    #thymelaf:
    #    cache: false

#H2 Configuration
spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
            dialect: org.hibernate.dialect.H2Dialect